2022-09-29 12:54:00.932589: Setting temporary cache path to shuffled_svm_out/cache
2022-09-29 12:54:00.932680: ImmuneML: parsing the specification...

Traceback (most recent call last):
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/bin/immune-ml", line 8, in <module>
    sys.exit(main())
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/site-packages/immuneML/app/ImmuneMLApp.py", line 89, in main
    run_immuneML(namespace)
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/site-packages/immuneML/app/ImmuneMLApp.py", line 74, in run_immuneML
    app.run()
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/site-packages/immuneML/app/ImmuneMLApp.py", line 44, in run
    symbol_table, self._specification_path = ImmuneMLParser.parse_yaml_file(self._specification_path, self._result_path)
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/site-packages/immuneML/dsl/ImmuneMLParser.py", line 107, in parse_yaml_file
    with file_path.open("r") as file:
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/nfs/scistore08/kondrgrp/aminnega/anaconda3/envs/ab-negative-training/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'shuffled_svm_test.yaml'
